[project]
name = "learn_nn"
version = "0.1.0"
description = "Add your description here"
readme = "readme.md"
requires-python = ">=3.9"
dependencies = [
    "addict>=2.4.0",
    "bottle>=0.13.4",
    "datasets>=4.5.0",
    "jieba>=0.42.1",
    "modelscope>=1.37.1",
    "numpy>=2.0.2",
    "nvitop>=1.7.1",
    "pillow>=11.3.0",
    "pytest>=8.4.2",
    "sentencepiece>=0.2.2",
    "tokenizers>=0.22.2",
    "torch>=2.8.0",
    "tqdm>=4.70.0",
    "transformers>=4.57.6",
    "zhconv>=1.4.3",
]

[project.scripts]
seq2seq = "learn_nn.models.seq2seq:main"
timformer = "learn_nn.models.transformer:main"
timllm-inference = "learn_nn.web_server.tim_llm_inference:main"
timllm = "learn_nn.models.mini_llm.train:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[tool.setuptools.packages.find]
where = ["src"]
