[project]
name = "learn_nn"
version = "0.1.0"
description = "Add your description here"
readme = "readme.md"
requires-python = ">=3.9"
dependencies = [
    "datasets>=4.5.0",
    "jieba>=0.42.1",
    "numpy>=2.0.2",
    "nvitop>=1.7.1",
    "torch>=2.8.0",
    "tqdm>=4.70.0",
    "zhconv>=1.4.3",
]

[project.scripts]
seq2seq = "learn_nn.models.seq2seq:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[tool.setuptools.packages.find]
where = ["src"]
